apiVersion: apps/v1
kind: Deployment
metadata:
  name: gfbfc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gfbfc
  template:
    metadata:
      labels:
        app: gfbfc
    spec:
      containers:
      - image: okteto.dev/gfbfc:latest
        name: gfbfc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "62ddd766-eb3a-4a2f-b3a7-986bc3af6d55"
        - name: Vless_Path
          value: "/vlfgs5"
        - name: Vmess_UUID
          value: "62ddd766-eb3a-4a2f-b3a7-986bc3af6d55"
        - name: Vmess_Path
          value: "/vmoui656"
        - name: Share_Path
          value: "/v2link"
